/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BioInput = IDL.Record({
  'activityLevel' : IDL.Nat,
  'sleepQuality' : IDL.Nat,
  'heartRate' : IDL.Nat,
  'timestamp' : Time,
  'geomagneticField' : IDL.Opt(IDL.Nat),
  'moonPhase' : IDL.Opt(IDL.Nat),
});
export const AlertLevel = IDL.Variant({
  'red' : IDL.Null,
  'blue' : IDL.Null,
  'yellow' : IDL.Null,
});
export const DreamJournalEntry = IDL.Record({
  'content' : IDL.Text,
  'date' : Time,
  'mood' : IDL.Opt(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
});
export const Ritual = IDL.Record({
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'schedule' : IDL.Vec(IDL.Nat),
  'timeOfDay' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Alert = IDL.Record({
  'level' : AlertLevel,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Settings = IDL.Record({
  'localOnly' : IDL.Bool,
  'ethicsAccepted' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBioInput' : IDL.Func([BioInput], [AlertLevel], []),
  'addDreamEntry' : IDL.Func([DreamJournalEntry], [], []),
  'addRitual' : IDL.Func([Ritual], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearUserData' : IDL.Func([], [], []),
  'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDreams' : IDL.Func([], [IDL.Vec(DreamJournalEntry)], ['query']),
  'getRituals' : IDL.Func([], [IDL.Vec(Ritual)], ['query']),
  'getSettings' : IDL.Func([], [IDL.Opt(Settings)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateSettings' : IDL.Func([Settings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BioInput = IDL.Record({
    'activityLevel' : IDL.Nat,
    'sleepQuality' : IDL.Nat,
    'heartRate' : IDL.Nat,
    'timestamp' : Time,
    'geomagneticField' : IDL.Opt(IDL.Nat),
    'moonPhase' : IDL.Opt(IDL.Nat),
  });
  const AlertLevel = IDL.Variant({
    'red' : IDL.Null,
    'blue' : IDL.Null,
    'yellow' : IDL.Null,
  });
  const DreamJournalEntry = IDL.Record({
    'content' : IDL.Text,
    'date' : Time,
    'mood' : IDL.Opt(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
  });
  const Ritual = IDL.Record({
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'schedule' : IDL.Vec(IDL.Nat),
    'timeOfDay' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Alert = IDL.Record({
    'level' : AlertLevel,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Settings = IDL.Record({
    'localOnly' : IDL.Bool,
    'ethicsAccepted' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBioInput' : IDL.Func([BioInput], [AlertLevel], []),
    'addDreamEntry' : IDL.Func([DreamJournalEntry], [], []),
    'addRitual' : IDL.Func([Ritual], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearUserData' : IDL.Func([], [], []),
    'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDreams' : IDL.Func([], [IDL.Vec(DreamJournalEntry)], ['query']),
    'getRituals' : IDL.Func([], [IDL.Vec(Ritual)], ['query']),
    'getSettings' : IDL.Func([], [IDL.Opt(Settings)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateSettings' : IDL.Func([Settings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };