/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'level' : AlertLevel,
  'message' : string,
  'timestamp' : Time,
}
export type AlertLevel = { 'red' : null } |
  { 'blue' : null } |
  { 'yellow' : null };
export interface BioInput {
  'activityLevel' : bigint,
  'sleepQuality' : bigint,
  'heartRate' : bigint,
  'timestamp' : Time,
  'geomagneticField' : [] | [bigint],
  'moonPhase' : [] | [bigint],
}
export interface DreamJournalEntry {
  'content' : string,
  'date' : Time,
  'mood' : [] | [string],
  'tags' : Array<string>,
}
export interface Ritual {
  'title' : string,
  'completed' : boolean,
  'description' : string,
  'schedule' : Array<bigint>,
  'timeOfDay' : [] | [bigint],
}
export interface Settings { 'localOnly' : boolean, 'ethicsAccepted' : boolean }
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBioInput' : ActorMethod<[BioInput], AlertLevel>,
  'addDreamEntry' : ActorMethod<[DreamJournalEntry], undefined>,
  'addRitual' : ActorMethod<[Ritual], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearUserData' : ActorMethod<[], undefined>,
  'getAlerts' : ActorMethod<[], Array<Alert>>,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDreams' : ActorMethod<[], Array<DreamJournalEntry>>,
  'getRituals' : ActorMethod<[], Array<Ritual>>,
  'getSettings' : ActorMethod<[], [] | [Settings]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateSettings' : ActorMethod<[Settings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];