/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DreamJournalEntry {
    content: string;
    date: Time;
    mood?: string;
    tags: Array<string>;
}
export interface Settings {
    localOnly: boolean;
    ethicsAccepted: boolean;
}
export type Time = bigint;
export interface BioInput {
    activityLevel: bigint;
    sleepQuality: bigint;
    heartRate: bigint;
    timestamp: Time;
    geomagneticField?: bigint;
    moonPhase?: bigint;
}
export interface Ritual {
    title: string;
    completed: boolean;
    description: string;
    schedule: Array<bigint>;
    timeOfDay?: bigint;
}
export interface Alert {
    level: AlertLevel;
    message: string;
    timestamp: Time;
}
export interface UserProfile {
    name: string;
}
export enum AlertLevel {
    red = "red",
    blue = "blue",
    yellow = "yellow"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBioInput(input: BioInput): Promise<AlertLevel>;
    addDreamEntry(entry: DreamJournalEntry): Promise<void>;
    addRitual(ritual: Ritual): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearUserData(): Promise<void>;
    getAlerts(): Promise<Array<Alert>>;
    getAllUsers(): Promise<Array<Principal>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDreams(): Promise<Array<DreamJournalEntry>>;
    getRituals(): Promise<Array<Ritual>>;
    getSettings(): Promise<Settings | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateSettings(settings: Settings): Promise<void>;
}
import type { Alert as _Alert, AlertLevel as _AlertLevel, BioInput as _BioInput, DreamJournalEntry as _DreamJournalEntry, Ritual as _Ritual, Settings as _Settings, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBioInput(arg0: BioInput): Promise<AlertLevel> {
        if (this.processError) {
            try {
                const result = await this.actor.addBioInput(to_candid_BioInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AlertLevel_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBioInput(to_candid_BioInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AlertLevel_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async addDreamEntry(arg0: DreamJournalEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDreamEntry(to_candid_DreamJournalEntry_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDreamEntry(to_candid_DreamJournalEntry_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addRitual(arg0: Ritual): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRitual(to_candid_Ritual_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRitual(to_candid_Ritual_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearUserData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearUserData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearUserData();
            return result;
        }
    }
    async getAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlerts();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlerts();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDreams(): Promise<Array<DreamJournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDreams();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDreams();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRituals(): Promise<Array<Ritual>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRituals();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRituals();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<Settings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateSettings(arg0: Settings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
}
function from_candid_AlertLevel_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertLevel): AlertLevel {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Alert_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_DreamJournalEntry_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DreamJournalEntry): DreamJournalEntry {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Ritual_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ritual): Ritual {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Settings]): Settings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    level: _AlertLevel;
    message: string;
    timestamp: _Time;
}): {
    level: AlertLevel;
    message: string;
    timestamp: Time;
} {
    return {
        level: from_candid_AlertLevel_n3(_uploadFile, _downloadFile, value.level),
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    date: _Time;
    mood: [] | [string];
    tags: Array<string>;
}): {
    content: string;
    date: Time;
    mood?: string;
    tags: Array<string>;
} {
    return {
        content: value.content,
        date: value.date,
        mood: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.mood)),
        tags: value.tags
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    completed: boolean;
    description: string;
    schedule: Array<bigint>;
    timeOfDay: [] | [bigint];
}): {
    title: string;
    completed: boolean;
    description: string;
    schedule: Array<bigint>;
    timeOfDay?: bigint;
} {
    return {
        title: value.title,
        completed: value.completed,
        description: value.description,
        schedule: value.schedule,
        timeOfDay: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.timeOfDay))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    blue: null;
} | {
    yellow: null;
}): AlertLevel {
    return "red" in value ? AlertLevel.red : "blue" in value ? AlertLevel.blue : "yellow" in value ? AlertLevel.yellow : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DreamJournalEntry>): Array<DreamJournalEntry> {
    return value.map((x)=>from_candid_DreamJournalEntry_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ritual>): Array<Ritual> {
    return value.map((x)=>from_candid_Ritual_n22(_uploadFile, _downloadFile, x));
}
function to_candid_BioInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BioInput): _BioInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_DreamJournalEntry_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DreamJournalEntry): _DreamJournalEntry {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Ritual_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Ritual): _Ritual {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activityLevel: bigint;
    sleepQuality: bigint;
    heartRate: bigint;
    timestamp: Time;
    geomagneticField?: bigint;
    moonPhase?: bigint;
}): {
    activityLevel: bigint;
    sleepQuality: bigint;
    heartRate: bigint;
    timestamp: _Time;
    geomagneticField: [] | [bigint];
    moonPhase: [] | [bigint];
} {
    return {
        activityLevel: value.activityLevel,
        sleepQuality: value.sleepQuality,
        heartRate: value.heartRate,
        timestamp: value.timestamp,
        geomagneticField: value.geomagneticField ? candid_some(value.geomagneticField) : candid_none(),
        moonPhase: value.moonPhase ? candid_some(value.moonPhase) : candid_none()
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    date: Time;
    mood?: string;
    tags: Array<string>;
}): {
    content: string;
    date: _Time;
    mood: [] | [string];
    tags: Array<string>;
} {
    return {
        content: value.content,
        date: value.date,
        mood: value.mood ? candid_some(value.mood) : candid_none(),
        tags: value.tags
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    completed: boolean;
    description: string;
    schedule: Array<bigint>;
    timeOfDay?: bigint;
}): {
    title: string;
    completed: boolean;
    description: string;
    schedule: Array<bigint>;
    timeOfDay: [] | [bigint];
} {
    return {
        title: value.title,
        completed: value.completed,
        description: value.description,
        schedule: value.schedule,
        timeOfDay: value.timeOfDay ? candid_some(value.timeOfDay) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
